# Generated by Django 5.1.2 on 2024-11-06 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        ('products', '0002_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Products', to='models.model', verbose_name='Model'),
            preserve_default=False,
        ),
    ]
