# Generated by Django 5.1.2 on 2024-10-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deactivated_by_admin',
        ),
    ]
