# Generated by Django 5.1.2 on 2024-10-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
    ]
